---
language: generic
services:
  - docker
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t varunaws22/user-wishlist .
  - docker images
  - docker push varunaws22/user-wishlist
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: pythonapplication
  env: Pythonapplication-env-1
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket_name: multi-container-user-wishlist
  bucket_path: docker
  on:
    branch: main